version: '3.8'

services:
  redis:
    image: redis:7.2.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=test@1234
    command: ["redis-server", "--requirepass", "test@1234"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test@1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
    driver: local
  mysql_data:
    driver: local
