spring:
  application:
    name: redis-jwt-example

  data:
    redis:
      host: localhost
      port: 6379
      password: ${password}
      lettuce:
        pool:
          max-active: 8
          max-idle: 5
          min-idle: 2
          max-wait: 1000ms